### ISSUE TITLE
Fixed element out of the pages is not fixed

### ISSUE THREAD

**Issue by Bbemol** [amondit/jquery.scrollsteps.js#1]
Hello,
Thanks for your great plugin.
I tried it and it worked well, but it seems like fixed elements out of the pages doesn't actually stick on the window, just like it's in relative position.
Have you noticed such issue ?
Thanks,
Bbemol

**Comment by amondit** [comment]
Hi,

Yes I've noticed that issue, however this seems not to be due to my plugin, but to how browser engines are managing fixed elements inside transformed elements (they also get transformed)...

More info here: http://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/

One way I found around the issue is to setup a fixed container element outside the translated container in the html tree.

Hope that helps !

Arnaud

**Comment by Bbemol** [comment]
Hey ! Yes, it solved my issue, indeed, transformation3d prevents the fixed elements. So I wrote something like : 

```
<div class="myFixedElement">
<div class="content">
<div class="fullScreenPage" id="page1">

</div>
<div class="fullScreenPage" id="page2">

</div>
</div>
</div>
```

And changed the element "body" in your javascript by ".content".
There it is ! Hope it can help someone else one day.
NB. : Don't forget to add transition to your new element to avoid the jump.

Merci encore pour ton plugin, ça m'a fait gagné pas mal de temps.
Salut ;)
